### ISSUE TITLE
[BUG] Issue Identifying song with multiple artists

### ISSUE THREAD

**Issue by conorhub** [SwagLyrics/SwagLyrics-For-Spotify#1479]
**Describe the bug**

Swaglyrics said it couldn't fetch the lyrics as _"That's a fishy request, that artist and song doesn't seem to exist on Spotify."_ despite the request being generated by the standard **'swaglyrics -t'** command. It correctly identified the song title and first artist in the browser above this message. The song has two artists listed under artist in spotify and I'm assuming this is causing an identification issue.

**To Reproduce**

 - Play the song https://open.spotify.com/track/4qCbMMMuEB56kHd4zPE6GD?si=K3ZSmMukQ2GT2uGHT9_pVA in spotify
 - Run 'swaglyrics -t'
 - The browser will suggest "That's a fishy request, that artist and song doesn't seem to exist on Spotify."

**Expected behavior**

I expected, at worst, the lyrics not to be available but not that the song would be described as possibly not existing on spotify.

**Desktop (please complete the following information):**

 - OS: macOS Mojave 10.14.5
 - spotify, latest version as of this date
 - swaglyrics, latest version as of downloading yesterday

**Additional context**

Many thanks for making swaglyrics, it's been very helpful since I discovered it. It works fine for me with other songs.

**Comment by aadibajpai** [comment]
Sorry for that Connor, I'll look into it!

**Comment by aadibajpai** [comment]
Interesting, other songs of that album are playable but this one seems blanked out.
![image](https://user-images.githubusercontent.com/27063113/59716975-a7a3df00-9234-11e9-8df4-1037519352aa.png)
![image](https://user-images.githubusercontent.com/27063113/59717799-5e548f00-9236-11e9-9b81-601f0f954263.png)

Whenever a song is received for whom lyrics can't be fetched in the first time (here because of multiple artists most probably) it is sent to the backend to try better methods. There's a check that queries the Spotify API to determine if it is actually legit so as to prevent spam. Since the song seems to be unplayable I presume that's where it mistook the request to be fishy. I think it might be available only in your locale?

Before that when it used the Genius API, the song is listed as "Long Road" instead of "The Long Road" on Genius so it didn't get info from there either. 

https://genius.com/Eddie-vedder-long-road-lyrics

This was definitely an edge case though, in future I'll work on making the comparison less strict so things like 'The' don't make a difference.

Anyway, it should be supported now. Do you mind trying once again?

Thanks for opening the issue, now I know what can be improved :)

**Comment by conorhub** [comment]
Thanks for the detailed explanation @aadibajpai and I hadn't considered the track could be region-locked (which is such a frustration in general, but I digress...). Just to confirm, it's not greyed out or locked in my location and may very well be what was causing the error, not that there was multiple artists.

The song does appear to be mistitled on Genius, as you pointed out, it's dropped 'the'.

It's working now. Many thanks

**Comment by aadibajpai** [comment]
The reason you didn't get the lyrics in the first place was the 'The', after that instead of saying lyrics unavailable, it said fishy request due to region locking. I added it to the backend database now so it wouldn't be a problem.

Glad to hear it's been resolved, @conorhub, thanks for opening the issue!
